//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azurlane.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Azurlane.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Azurlane.ini v2.6
        ///#Ignore meaning no modification will be made towards the said attribute
        ///
        ///[Common]
        ///CreateWeakEnemy=True
        ///CreateGodMode=True
        ///CreateGodModeCooldown=True
        ///CreateGodModeDamage=True
        ///CreateGodModeDamageCooldown=True
        ///CreateGodModeWeakEnemy=True
        ///
        ///# ------------------------------------------------------ #
        ///
        ///[Player]
        ///# Implemented in the near future #
        ///PlayerReplaceSkin=False
        ///Skin=Gridley:101051, Craven:101061, Hammann:101251, Eldridge:101262, Nicholas:101311, San Diego:102081, Cleveland [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Azurlane {
            get {
                return ResourceManager.GetString("Azurlane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Lock {
            get {
                object obj = ResourceManager.GetObject("Lock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Salt {
            get {
                object obj = ResourceManager.GetObject("Salt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USS Gridley 
        ///Default Skin: 101050
        ///Xmas Skin: 101051
        ///
        ///USS Craven
        ///Default Skin: 101060
        ///School Skin: 101061
        ///
        ///USS Hammann
        ///Default Skin: 101250
        ///Summer Skin: 101251
        ///
        ///USS Eldridge
        ///Default Skin: 101260
        ///Xmas Skin: 101261
        ///School Skin: 101262
        ///
        ///USS Nicholas
        ///Default Skin: 101310
        ///Nurse Skin: 101311
        ///
        ///USS San Diego
        ///Default Skin: 102080
        ///Xmas Skin: 102081
        ///
        ///USS Cleveland
        ///Default Skin: 102090
        ///Halloween Skin: 102091
        ///
        ///USS Honolulu
        ///Default Skin: 102120
        ///School Skin: 102121
        ///
        ///USS St.Louis
        ///Default Sk [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Skins {
            get {
                return ResourceManager.GetString("Skins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Unlock {
            get {
                object obj = ResourceManager.GetObject("Unlock", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
